CREATE TABLE IF NOT EXISTS model (
    idx INT NOT NULL AUTO_INCREMENT,
    name CHAR(100) NOT NULL,
    positions JSON NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (idx)
) ENGINE=InnoDB CHARACTER SET=utf8mb4;

CREATE TABLE IF NOT EXISTS modl (
    idx INT NOT NULL AUTO_INCREMENT,
    name CHAR(100) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),

    PRIMARY KEY (idx)
) ENGINE=InnoDB CHARACTER SET=utf8mb4;